// Content-level translation layer for homepage section content (cards, chips,
// feature lists) that lives outside the main i18n key system.
// Keys are the exact English strings used in components; missing entries fall
// back to English. Currently translated: FR, AR, SO. Add more languages by
// adding a dictionary — no component changes needed.
import type { LangCode } from './i18n'

type Dict = Record<string, string>

const FR: Dict = {
  // ── TrustBar ──
  'Government ID Verification': 'Vérification de pièce d\'identité',
  'Face Verification': 'Vérification faciale',
  'Phone Verification': 'Vérification du téléphone',
  'Marriage Intent Screening': 'Contrôle de l\'intention de mariage',
  'Scam Detection': 'Détection des arnaques',
  'Family Participation': 'Participation de la famille',
  'Human Moderation': 'Modération humaine',
  'Privacy Controls': 'Contrôles de confidentialité',
  'No Casual Dating': 'Pas de rencontres occasionnelles',
  // ── Hero ──
  'Profiles reviewed': 'Profils vérifiés',
  'Report response': 'Réponse aux signalements',
  'Countries served': 'Pays desservis',
  '🪪 ID-Verified Members': '🪪 Membres à identité vérifiée',
  '👨‍👩‍👧 Family & Wali Involved': '👨‍👩‍👧 Famille et wali impliqués',
  '🕌 Marriage Intent Screened': '🕌 Intention de mariage contrôlée',
  '🚫 No Casual Dating': '🚫 Pas de rencontres occasionnelles',
  'Serving Muslim communities in 50+ countries': 'Au service des communautés musulmanes dans plus de 50 pays',
  // ── WhyNikah ──
  '⚠️ Why Nikah Exists': '⚠️ Pourquoi Nikah existe',
  'The Problems Other Platforms Ignore': 'Les problèmes que les autres plateformes ignorent',
  'Muslims seeking marriage deserve better than fake profiles, scams, and casual chatting. Nikah was built to remove each of these obstacles.': 'Les musulmans en quête de mariage méritent mieux que les faux profils, les arnaques et les discussions sans but. Nikah a été conçu pour éliminer chacun de ces obstacles.',
  'Fake profiles': 'Faux profils',
  'Scammers': 'Arnaqueurs',
  'Endless messaging with no outcome': 'Messages sans fin, sans résultat',
  'Unsafe interactions': 'Interactions non sécurisées',
  'Families left out': 'Familles mises à l\'écart',
  'No serious marriage intent': 'Aucune intention sérieuse de mariage',
  'Every member completes government ID, face, and phone verification before they can freely interact.': 'Chaque membre complète la vérification d\'identité, faciale et téléphonique avant de pouvoir interagir librement.',
  'AI risk scoring, message pattern detection, and human review catch money requests and romance scams early.': 'Score de risque IA, détection des schémas de messages et examen humain repèrent tôt les demandes d\'argent et les arnaques sentimentales.',
  'Structured introductions with marriage timelines, so conversations move toward a decision — not years of chatting.': 'Des présentations structurées avec un calendrier de mariage, pour que les conversations mènent à une décision — pas des années de discussion.',
  'Chaperoned conversations, photo protection, consent-based messaging, and moderators who answer reports within 24 hours.': 'Conversations chaperonnées, protection des photos, messagerie basée sur le consentement et modérateurs qui répondent aux signalements sous 24 heures.',
  'Wali and parent accounts, family review of proposals, and a family dashboard — involvement is built in, not bolted on.': 'Comptes wali et parents, examen familial des propositions et tableau de bord familial — l\'implication est intégrée dès la conception.',
  'Marriage intent screening and readiness badges filter out anyone who is not genuinely pursuing Nikah.': 'Le contrôle de l\'intention de mariage et les badges de préparation écartent quiconque ne recherche pas sincèrement le Nikah.',
  // ── HowItWorks ──
  'Create a Verified Profile': 'Créez un profil vérifié',
  'Build a marriage-focused profile stating your faith, values, family expectations, and marriage intentions — reviewed before it goes live.': 'Créez un profil axé sur le mariage indiquant votre foi, vos valeurs, vos attentes familiales et vos intentions — examiné avant publication.',
  'Marriage intent stated upfront': 'Intention de mariage déclarée d\'emblée',
  'Profile reviewed by a human': 'Profil examiné par un humain',
  'Photo privacy controls': 'Contrôle de confidentialité des photos',
  'Verify Your Identity': 'Vérifiez votre identité',
  'Complete government ID, face, and phone verification. Every member you meet is a real, accountable person — no anonymous profiles.': 'Complétez la vérification d\'identité, faciale et téléphonique. Chaque membre que vous rencontrez est une personne réelle et responsable — aucun profil anonyme.',
  'Government ID check': 'Contrôle de pièce d\'identité',
  'Face verification': 'Vérification faciale',
  'Phone verification': 'Vérification du téléphone',
  'Complete Your Marriage Assessment': 'Complétez votre évaluation de mariage',
  'Answer marriage-readiness and compatibility questions covering deen, prayer, madhab, family values, children, finances, and timeline.': 'Répondez aux questions de préparation au mariage et de compatibilité : deen, prière, madhab, valeurs familiales, enfants, finances et calendrier.',
  'Marriage readiness score': 'Score de préparation au mariage',
  'Faith & values assessment': 'Évaluation foi et valeurs',
  'Marriage timeline': 'Calendrier de mariage',
  'Receive Marriage Candidates': 'Recevez des candidats au mariage',
  'We introduce you only to verified, compatible candidates who share your marriage timeline — with a compatibility score explained for each.': 'Nous ne vous présentons que des candidats vérifiés et compatibles partageant votre calendrier de mariage — avec un score de compatibilité expliqué pour chacun.',
  'Verified candidates only': 'Candidats vérifiés uniquement',
  'Compatibility explained': 'Compatibilité expliquée',
  'Filter by readiness': 'Filtrer par préparation',
  'Begin Introductions': 'Commencez les présentations',
  'Start a chaperoned or private introduction with clear guidelines. Conversations are purpose-driven and protected by moderation.': 'Commencez une présentation chaperonnée ou privée avec des règles claires. Les conversations ont un but précis et sont protégées par la modération.',
  'Chaperoned option': 'Option chaperonnée',
  'Consent-based messaging': 'Messagerie basée sur le consentement',
  'Moderated conversations': 'Conversations modérées',
  'Involve Families & Proceed to Nikah': 'Impliquez les familles et avancez vers le Nikah',
  'Invite your wali, parents, or trusted family into the conversation and move toward Nikah with full transparency and Allah\'s blessing.': 'Invitez votre wali, vos parents ou votre famille de confiance dans la conversation et avancez vers le Nikah en toute transparence, avec la bénédiction d\'Allah.',
  'Wali/family invite': 'Invitation wali/famille',
  'Family review of proposals': 'Examen familial des propositions',
  'Guided steps to Nikah': 'Étapes guidées vers le Nikah',
  'No credit card required · Cancel anytime': 'Aucune carte bancaire requise · Annulez à tout moment',
  // ── Safety ──
  'Members verify with a government-issued ID, face verification, and phone number — so every person you meet is real and accountable.': 'Les membres se vérifient avec une pièce d\'identité officielle, une vérification faciale et un numéro de téléphone — chaque personne rencontrée est réelle et responsable.',
  'AI Fraud Detection': 'Détection de fraude par IA',
  'Automated systems score risk, detect scam patterns like money requests and mass messaging, and restrict suspicious accounts before harm is done.': 'Des systèmes automatisés évaluent le risque, détectent les schémas d\'arnaque (demandes d\'argent, messages de masse) et restreignent les comptes suspects avant tout préjudice.',
  'A dedicated trust and safety team reviews every profile, every flagged conversation, and every verification submission — not just algorithms.': 'Une équipe dédiée à la confiance et à la sécurité examine chaque profil, chaque conversation signalée et chaque vérification — pas seulement des algorithmes.',
  'Reports Answered in 24 Hours': 'Signalements traités en 24 heures',
  'Report suspicious or inappropriate behavior instantly. A human moderator responds to every report within 24 hours.': 'Signalez instantanément tout comportement suspect ou inapproprié. Un modérateur humain répond à chaque signalement sous 24 heures.',
  'Photo Protection': 'Protection des photos',
  'Photos are blurred by default and screenshots are discouraged. You approve exactly who can see your image — your photo, your control.': 'Les photos sont floutées par défaut. Vous approuvez précisément qui peut voir votre image — votre photo, votre contrôle.',
  'Private photo albums, hidden mode, granular visibility settings, and family-only viewing options protect you at every stage.': 'Albums photo privés, mode masqué, paramètres de visibilité précis et affichage réservé à la famille vous protègent à chaque étape.',
  'Wali & Chaperone Mode': 'Mode wali et chaperon',
  'Invite a wali, parent, or trusted family member into any conversation for a fully transparent, family-supervised process.': 'Invitez un wali, un parent ou un proche de confiance dans toute conversation pour un processus totalement transparent et supervisé par la famille.',
  'Block & Restrict Tools': 'Outils de blocage et de restriction',
  'Block anyone instantly without explanation. Restrict who can contact you to verified members only. Clear community guidelines, enforced.': 'Bloquez qui vous voulez instantanément, sans justification. Limitez les contacts aux membres vérifiés. Des règles communautaires claires, appliquées.',
  'Our safety commitments to': 'Nos engagements de sécurité envers',
  'every member': 'chaque membre',
  'Human moderators operate across time zones. These are standards we hold ourselves to — published in our Trust Center.': 'Des modérateurs humains opèrent sur tous les fuseaux horaires. Ce sont des normes que nous nous imposons — publiées dans notre Centre de confiance.',
  'Profiles human-reviewed': 'Profils examinés par un humain',
  'Report response time': 'Délai de réponse aux signalements',
  'Tolerance for money requests': 'Tolérance pour les demandes d\'argent',
  'Data compliant': 'Conforme RGPD',
  'Visit the Trust Center': 'Visiter le Centre de confiance',
  // ── Compatibility ──
  '🧭 Marriage Compatibility': '🧭 Compatibilité de mariage',
  'Compatibility Measured on What Marriage Is Built On': 'Une compatibilité mesurée sur les fondements du mariage',
  'Not photos and small talk — deen, family, children, finances, and timeline.': 'Pas des photos et des banalités — le deen, la famille, les enfants, les finances et le calendrier.',
  'Every score is explained, so you understand': 'Chaque score est expliqué, pour que vous compreniez',
  'why': 'pourquoi',
  'a candidate is compatible.': 'un candidat est compatible.',
  'Assessed across 15 marriage dimensions': 'Évalué sur 15 dimensions du mariage',
  'Deen & practice': 'Deen et pratique', 'Prayer frequency': 'Fréquence de prière', 'Madhab': 'Madhab',
  'Islamic knowledge': 'Connaissances islamiques', 'Family values': 'Valeurs familiales',
  'Children preference': 'Préférence enfants', 'Family involvement': 'Implication familiale',
  'Living arrangements': 'Mode de vie', 'Career goals': 'Objectifs de carrière', 'Education': 'Éducation',
  'Location': 'Localisation', 'Financial expectations': 'Attentes financières',
  'Traditional vs modern roles': 'Rôles traditionnels vs modernes', 'Relocation willingness': 'Volonté de déménager',
  'Compatibility Report': 'Rapport de compatibilité', '(example)': '(exemple)',
  'You complete the assessment once during onboarding. We then introduce you only to verified candidates whose answers align with yours — and show you exactly where you align and where you differ, so families can make informed decisions together.': 'Vous complétez l\'évaluation une fois lors de l\'inscription. Nous ne vous présentons ensuite que des candidats vérifiés dont les réponses correspondent aux vôtres — en montrant précisément vos points d\'accord et de différence, pour que les familles décident en connaissance de cause.',
  'Deen & prayer': 'Deen et prière',
  'Both pray five times daily and follow the same madhab': 'Tous deux prient cinq fois par jour et suivent le même madhab',
  'Both want family closely involved from the first introduction': 'Tous deux veulent une famille impliquée dès la première présentation',
  'Children & household': 'Enfants et foyer',
  'Aligned on children within 2 years and shared responsibilities': 'Alignés sur des enfants d\'ici 2 ans et des responsabilités partagées',
  'Both ready for Nikah within 12 months': 'Tous deux prêts pour le Nikah d\'ici 12 mois',
  'Location & relocation': 'Localisation et déménagement',
  'Same city; one is open to relocating after marriage': 'Même ville ; l\'un est ouvert à déménager après le mariage',
  // ── MarriageReadiness ──
  '🎖️ Marriage Readiness': '🎖️ Préparation au mariage',
  'Know Who Is Actually Ready for Nikah': 'Sachez qui est réellement prêt pour le Nikah',
  'Every member earns a Marriage Readiness badge based on verified behavior — not self-promotion. Filter your candidates by readiness so no one wastes your time.': 'Chaque membre obtient un badge de préparation basé sur un comportement vérifié — pas sur l\'autopromotion. Filtrez vos candidats par niveau de préparation pour ne pas perdre de temps.',
  'Ready Now': 'Prêt maintenant', 'Within 12 Months': 'D\'ici 12 mois', 'Exploring Marriage': 'Explore le mariage',
  'Family Involved': 'Famille impliquée', 'Fully Verified': 'Entièrement vérifié',
  'Fully prepared for Nikah and actively seeking': 'Entièrement prêt pour le Nikah et en recherche active',
  'Committed to marriage within the coming year': 'Engagé à se marier dans l\'année à venir',
  'Serious about marriage, still defining the timeline': 'Sérieux sur le mariage, calendrier en cours de définition',
  'Wali or family actively participating in the search': 'Wali ou famille participant activement à la recherche',
  'ID, face, and phone verification all complete': 'Vérifications identité, faciale et téléphone complètes',
  'Your readiness score is built from:': 'Votre score de préparation est calculé à partir de :',
  'Verification completion': 'Vérifications complétées', 'Profile completeness': 'Profil complété',
  'Marriage intent assessment': 'Évaluation de l\'intention de mariage', 'Lifestyle assessment': 'Évaluation du mode de vie',
  'Financial stability questions': 'Questions de stabilité financière',
  'Communication behavior': 'Comportement de communication',
  // ── FamilyParticipation ──
  '👨‍👩‍👧 Family Participation': '👨‍👩‍👧 Participation familiale',
  'Marriage Is a Family Matter — So Is Nikah': 'Le mariage est une affaire de famille — Nikah aussi',
  'The only platform where wali and family involvement is a first-class feature, not an afterthought. Every family tool is optional and controlled by you.': 'La seule plateforme où l\'implication du wali et de la famille est une fonctionnalité de premier plan, pas une option ajoutée. Chaque outil familial est facultatif et sous votre contrôle.',
  'Parent Accounts': 'Comptes parents',
  'Parents can hold their own linked account to follow and support the search.': 'Les parents peuvent avoir leur propre compte lié pour suivre et soutenir la recherche.',
  'Wali Participation': 'Participation du wali',
  'A wali can be invited into any introduction from the very first message.': 'Un wali peut être invité à toute présentation dès le premier message.',
  'Family-Assisted Search': 'Recherche assistée par la famille',
  'Family members can browse and shortlist candidates on your behalf.': 'Les membres de la famille peuvent parcourir et présélectionner des candidats pour vous.',
  'Family Review of Proposals': 'Examen familial des propositions',
  'Proposals can require family approval before an introduction begins.': 'Les propositions peuvent exiger l\'accord de la famille avant toute présentation.',
  'Chaperoned Conversations': 'Conversations chaperonnées',
  'Conversations can include a chaperone who sees every message.': 'Les conversations peuvent inclure un chaperon qui voit chaque message.',
  'Family Dashboard': 'Tableau de bord familial',
  'A dedicated view of active introductions, proposals, and progress.': 'Une vue dédiée des présentations actives, des propositions et des progrès.',
  'Suggestions for Parents': 'Suggestions pour les parents',
  'Compatible candidate suggestions parents can pass to their son or daughter.': 'Des suggestions de candidats compatibles que les parents peuvent transmettre à leur fils ou fille.',
  'Family Visibility Settings': 'Paramètres de visibilité familiale',
  'You choose exactly what your family can see — full, partial, or summary.': 'Vous choisissez précisément ce que votre famille peut voir — tout, partiel ou résumé.',
  // ── AntiScam ──
  '🚫 Our Anti-Scam Commitment': '🚫 Notre engagement anti-arnaque',
  'Zero Tolerance. Enforced by Systems and People.': 'Tolérance zéro. Appliquée par des systèmes et des personnes.',
  'Marriage scams target hopeful people at their most trusting. We treat scam prevention as a core product feature — not a help-center page.': 'Les arnaques au mariage ciblent des personnes pleines d\'espoir au moment où elles font le plus confiance. La prévention des arnaques est pour nous une fonctionnalité centrale — pas une page d\'aide.',
  'Never allowed on Nikah': 'Jamais autorisé sur Nikah',
  'Requests for money': 'Demandes d\'argent',
  'Gift card requests': 'Demandes de cartes cadeaux',
  'Crypto or investment schemes': 'Arnaques crypto ou d\'investissement',
  'Fake overseas marriage requests': 'Fausses demandes de mariage à l\'étranger',
  'Unverified profiles messaging freely': 'Messagerie libre pour profils non vérifiés',
  'Multiple hidden accounts': 'Comptes cachés multiples',
  'Harassment of any kind': 'Harcèlement de toute nature',
  'Suspicious mass messaging': 'Messages de masse suspects',
  'Automatic Detection & Risk Scoring': 'Détection automatique et score de risque',
  'Message patterns, account behavior, and reports feed a risk score. High-risk accounts are flagged before they can reach more members.': 'Les schémas de messages, le comportement du compte et les signalements alimentent un score de risque. Les comptes à haut risque sont signalés avant de pouvoir atteindre d\'autres membres.',
  'Warnings & Restrictions': 'Avertissements et restrictions',
  'Risky behavior triggers warnings and messaging restrictions immediately — a suspicious account cannot keep contacting people while under review.': 'Un comportement à risque déclenche immédiatement avertissements et restrictions — un compte suspect ne peut pas continuer à contacter des membres pendant son examen.',
  'Manual Review & Permanent Bans': 'Examen manuel et bannissements définitifs',
  'A human moderator reviews every flagged account. Confirmed scammers are permanently banned and their verification details blocked from re-registering.': 'Un modérateur humain examine chaque compte signalé. Les arnaqueurs confirmés sont bannis définitivement et leurs données de vérification bloquées pour empêcher toute réinscription.',
  'Refunds When Applicable': 'Remboursements le cas échéant',
  'If a paying member is harmed by a failure of our safety systems, we review the case for a refund. We stand behind our protection.': 'Si un membre payant est lésé par une défaillance de nos systèmes de sécurité, nous étudions un remboursement. Nous assumons notre protection.',
  // ── Transparency ──
  '📊 Transparency': '📊 Transparence',
  'We Publish the Numbers That Matter': 'Nous publions les chiffres qui comptent',
  'No inflated member counts. As the platform grows, these metrics are reported live and audited in our annual transparency report.': 'Pas de nombres de membres gonflés. À mesure que la plateforme grandit, ces indicateurs sont publiés en direct et audités dans notre rapport annuel de transparence.',
  'Verified profile percentage': 'Pourcentage de profils vérifiés',
  'Successful marriages reported': 'Mariages réussis rapportés',
  'Average first response time': 'Délai moyen de première réponse',
  'Scam reports resolved < 24h': 'Signalements d\'arnaque résolus < 24 h',
  'Profile approval rate': 'Taux d\'approbation des profils',
  'Fraud attempts blocked': 'Tentatives de fraude bloquées',
  'Languages supported': 'Langues prises en charge',
  'Metrics marked “—” will display live data at launch. We do not publish estimates or invented figures.': 'Les indicateurs marqués « — » afficheront des données réelles au lancement. Nous ne publions ni estimations ni chiffres inventés.',
  // ── TrustCenterPreview ──
  'Everything We Do Is Documented in the Trust Center': 'Tout ce que nous faisons est documenté dans le Centre de confiance',
  'How verification works, how moderation decisions are made, how your data is protected, and how we report on it — all public, all in one place.': 'Comment fonctionne la vérification, comment sont prises les décisions de modération, comment vos données sont protégées et comment nous en rendons compte — tout est public, au même endroit.',
  'Verification Standards': 'Normes de vérification',
  'Scam Prevention': 'Prévention des arnaques',
  'Moderation Process': 'Processus de modération',
  'Data Privacy': 'Confidentialité des données',
  'Community Guidelines': 'Règles communautaires',
  'Transparency Reports': 'Rapports de transparence',
  'Visit the Trust Center →': 'Visiter le Centre de confiance →',
}

const AR: Dict = {
  'Government ID Verification': 'التحقق من الهوية الحكومية',
  'Face Verification': 'التحقق من الوجه',
  'Phone Verification': 'التحقق من الهاتف',
  'Marriage Intent Screening': 'فحص نية الزواج',
  'Scam Detection': 'كشف الاحتيال',
  'Family Participation': 'مشاركة الأسرة',
  'Human Moderation': 'إشراف بشري',
  'Privacy Controls': 'ضوابط الخصوصية',
  'No Casual Dating': 'لا مواعدة عابرة',
  'Profiles reviewed': 'ملفات تمت مراجعتها',
  'Report response': 'الرد على البلاغات',
  'Countries served': 'دولة مخدومة',
  '🪪 ID-Verified Members': '🪪 أعضاء موثقو الهوية',
  '👨‍👩‍👧 Family & Wali Involved': '👨‍👩‍👧 مشاركة الأسرة والولي',
  '🕌 Marriage Intent Screened': '🕌 نية الزواج مفحوصة',
  '🚫 No Casual Dating': '🚫 لا مواعدة عابرة',
  'Serving Muslim communities in 50+ countries': 'نخدم المجتمعات المسلمة في أكثر من 50 دولة',
  '⚠️ Why Nikah Exists': '⚠️ لماذا وُجد نكاح',
  'The Problems Other Platforms Ignore': 'المشاكل التي تتجاهلها المنصات الأخرى',
  'Muslims seeking marriage deserve better than fake profiles, scams, and casual chatting. Nikah was built to remove each of these obstacles.': 'المسلمون الباحثون عن الزواج يستحقون أفضل من الملفات المزيفة والاحتيال والدردشة بلا هدف. بُني نكاح لإزالة كل عقبة من هذه العقبات.',
  'Fake profiles': 'الملفات المزيفة',
  'Scammers': 'المحتالون',
  'Endless messaging with no outcome': 'مراسلات لا تنتهي بلا نتيجة',
  'Unsafe interactions': 'تفاعلات غير آمنة',
  'Families left out': 'إقصاء الأسرة',
  'No serious marriage intent': 'غياب نية الزواج الجادة',
  'Every member completes government ID, face, and phone verification before they can freely interact.': 'يُكمل كل عضو التحقق من الهوية والوجه والهاتف قبل أن يتمكن من التفاعل بحرية.',
  'AI risk scoring, message pattern detection, and human review catch money requests and romance scams early.': 'تقييم المخاطر بالذكاء الاصطناعي وكشف أنماط الرسائل والمراجعة البشرية تكشف طلبات المال والاحتيال العاطفي مبكراً.',
  'Structured introductions with marriage timelines, so conversations move toward a decision — not years of chatting.': 'تعارف منظم بجداول زمنية للزواج، لتتجه المحادثات نحو قرار — لا سنوات من الدردشة.',
  'Chaperoned conversations, photo protection, consent-based messaging, and moderators who answer reports within 24 hours.': 'محادثات بمرافقة، حماية للصور، مراسلة بالموافقة، ومشرفون يردون على البلاغات خلال 24 ساعة.',
  'Wali and parent accounts, family review of proposals, and a family dashboard — involvement is built in, not bolted on.': 'حسابات للولي والوالدين، مراجعة أسرية للعروض، ولوحة أسرية — المشاركة مدمجة في التصميم لا مضافة.',
  'Marriage intent screening and readiness badges filter out anyone who is not genuinely pursuing Nikah.': 'فحص نية الزواج وشارات الجاهزية تستبعد كل من لا يسعى للنكاح بصدق.',
  'Create a Verified Profile': 'أنشئ ملفاً موثقاً',
  'Build a marriage-focused profile stating your faith, values, family expectations, and marriage intentions — reviewed before it goes live.': 'أنشئ ملفاً يركز على الزواج يوضح إيمانك وقيمك وتوقعاتك الأسرية ونواياك — يُراجع قبل نشره.',
  'Marriage intent stated upfront': 'نية الزواج معلنة من البداية',
  'Profile reviewed by a human': 'الملف يراجعه إنسان',
  'Photo privacy controls': 'ضوابط خصوصية الصور',
  'Verify Your Identity': 'وثّق هويتك',
  'Complete government ID, face, and phone verification. Every member you meet is a real, accountable person — no anonymous profiles.': 'أكمل التحقق من الهوية والوجه والهاتف. كل عضو تقابله شخص حقيقي ومسؤول — لا ملفات مجهولة.',
  'Government ID check': 'فحص الهوية الحكومية',
  'Face verification': 'التحقق من الوجه',
  'Phone verification': 'التحقق من الهاتف',
  'Complete Your Marriage Assessment': 'أكمل تقييم الزواج',
  'Answer marriage-readiness and compatibility questions covering deen, prayer, madhab, family values, children, finances, and timeline.': 'أجب عن أسئلة الجاهزية للزواج والتوافق: الدين والصلاة والمذهب والقيم الأسرية والأطفال والمال والجدول الزمني.',
  'Marriage readiness score': 'درجة الجاهزية للزواج',
  'Faith & values assessment': 'تقييم الإيمان والقيم',
  'Marriage timeline': 'الجدول الزمني للزواج',
  'Receive Marriage Candidates': 'استقبل مرشحين للزواج',
  'We introduce you only to verified, compatible candidates who share your marriage timeline — with a compatibility score explained for each.': 'نعرّفك فقط على مرشحين موثقين ومتوافقين يشاركونك الجدول الزمني للزواج — مع شرح درجة التوافق لكل منهم.',
  'Verified candidates only': 'مرشحون موثقون فقط',
  'Compatibility explained': 'توافق مُفسَّر',
  'Filter by readiness': 'التصفية حسب الجاهزية',
  'Begin Introductions': 'ابدأ التعارف',
  'Start a chaperoned or private introduction with clear guidelines. Conversations are purpose-driven and protected by moderation.': 'ابدأ تعارفاً بمرافقة أو خاصاً وفق ضوابط واضحة. المحادثات هادفة ومحمية بالإشراف.',
  'Chaperoned option': 'خيار المرافقة',
  'Consent-based messaging': 'مراسلة بالموافقة',
  'Moderated conversations': 'محادثات خاضعة للإشراف',
  'Involve Families & Proceed to Nikah': 'أشرك الأسرتين وامضِ نحو النكاح',
  'Invite your wali, parents, or trusted family into the conversation and move toward Nikah with full transparency and Allah\'s blessing.': 'ادعُ وليّك أو والديك أو أسرتك الموثوقة إلى المحادثة وامضِ نحو النكاح بشفافية كاملة وببركة الله.',
  'Wali/family invite': 'دعوة الولي/الأسرة',
  'Family review of proposals': 'مراجعة أسرية للعروض',
  'Guided steps to Nikah': 'خطوات موجهة نحو النكاح',
  'No credit card required · Cancel anytime': 'لا حاجة لبطاقة ائتمان · إلغاء في أي وقت',
  'Members verify with a government-issued ID, face verification, and phone number — so every person you meet is real and accountable.': 'يتحقق الأعضاء بهوية حكومية وتحقق من الوجه ورقم هاتف — فكل شخص تقابله حقيقي ومسؤول.',
  'AI Fraud Detection': 'كشف الاحتيال بالذكاء الاصطناعي',
  'Automated systems score risk, detect scam patterns like money requests and mass messaging, and restrict suspicious accounts before harm is done.': 'أنظمة آلية تقيّم المخاطر وتكشف أنماط الاحتيال كطلبات المال والرسائل الجماعية، وتقيّد الحسابات المشبوهة قبل وقوع الضرر.',
  'A dedicated trust and safety team reviews every profile, every flagged conversation, and every verification submission — not just algorithms.': 'فريق متخصص للثقة والسلامة يراجع كل ملف وكل محادثة مُبلغ عنها وكل طلب توثيق — لا خوارزميات فحسب.',
  'Reports Answered in 24 Hours': 'الرد على البلاغات خلال 24 ساعة',
  'Report suspicious or inappropriate behavior instantly. A human moderator responds to every report within 24 hours.': 'أبلغ فوراً عن أي سلوك مشبوه أو غير لائق. مشرف بشري يرد على كل بلاغ خلال 24 ساعة.',
  'Photo Protection': 'حماية الصور',
  'Photos are blurred by default and screenshots are discouraged. You approve exactly who can see your image — your photo, your control.': 'الصور مموهة افتراضياً. أنت من يحدد بدقة من يرى صورتك — صورتك، وقرارك.',
  'Private photo albums, hidden mode, granular visibility settings, and family-only viewing options protect you at every stage.': 'ألبومات خاصة، وضع مخفي، إعدادات ظهور دقيقة، وخيارات عرض للأسرة فقط تحميك في كل مرحلة.',
  'Wali & Chaperone Mode': 'وضع الولي والمرافق',
  'Invite a wali, parent, or trusted family member into any conversation for a fully transparent, family-supervised process.': 'ادعُ ولياً أو أحد الوالدين أو قريباً موثوقاً إلى أي محادثة لعملية شفافة بإشراف أسري كامل.',
  'Block & Restrict Tools': 'أدوات الحظر والتقييد',
  'Block anyone instantly without explanation. Restrict who can contact you to verified members only. Clear community guidelines, enforced.': 'احظر أي شخص فوراً دون تفسير. اقصر التواصل معك على الأعضاء الموثقين. قواعد مجتمع واضحة ومطبقة.',
  'Our safety commitments to': 'التزاماتنا الأمنية تجاه',
  'every member': 'كل عضو',
  'Human moderators operate across time zones. These are standards we hold ourselves to — published in our Trust Center.': 'مشرفون بشريون يعملون عبر المناطق الزمنية. هذه معايير نلتزم بها — منشورة في مركز الثقة.',
  'Profiles human-reviewed': 'ملفات يراجعها البشر',
  'Report response time': 'زمن الرد على البلاغات',
  'Tolerance for money requests': 'التسامح مع طلبات المال',
  'Data compliant': 'متوافق مع حماية البيانات',
  'Visit the Trust Center': 'زر مركز الثقة',
  '🧭 Marriage Compatibility': '🧭 التوافق الزواجي',
  'Compatibility Measured on What Marriage Is Built On': 'توافق يُقاس على ما يُبنى عليه الزواج',
  'Not photos and small talk — deen, family, children, finances, and timeline.': 'ليس الصور والأحاديث العابرة — بل الدين والأسرة والأطفال والمال والجدول الزمني.',
  'Every score is explained, so you understand': 'كل درجة مُفسَّرة، لتفهم',
  'why': 'لماذا',
  'a candidate is compatible.': 'المرشح متوافق.',
  'Assessed across 15 marriage dimensions': 'تقييم عبر 15 بعداً زواجياً',
  'Deen & practice': 'الدين والممارسة', 'Prayer frequency': 'المواظبة على الصلاة', 'Madhab': 'المذهب',
  'Islamic knowledge': 'العلم الشرعي', 'Family values': 'القيم الأسرية',
  'Children preference': 'الرغبة في الأطفال', 'Family involvement': 'مشاركة الأسرة',
  'Living arrangements': 'ترتيبات السكن', 'Career goals': 'الأهداف المهنية', 'Education': 'التعليم',
  'Location': 'الموقع', 'Financial expectations': 'التوقعات المالية',
  'Traditional vs modern roles': 'الأدوار التقليدية والحديثة', 'Relocation willingness': 'الاستعداد للانتقال',
  'Compatibility Report': 'تقرير التوافق', '(example)': '(مثال)',
  'You complete the assessment once during onboarding. We then introduce you only to verified candidates whose answers align with yours — and show you exactly where you align and where you differ, so families can make informed decisions together.': 'تُكمل التقييم مرة واحدة عند التسجيل، ثم نعرض عليك فقط مرشحين موثقين تتوافق إجاباتهم مع إجاباتك — ونبين لك مواضع التوافق والاختلاف بدقة لتتخذ الأسرتان قراراً مستنيراً.',
  'Deen & prayer': 'الدين والصلاة',
  'Both pray five times daily and follow the same madhab': 'كلاهما يصلي الخمس ويتبع المذهب نفسه',
  'Both want family closely involved from the first introduction': 'كلاهما يريد مشاركة الأسرة منذ أول تعارف',
  'Children & household': 'الأطفال والبيت',
  'Aligned on children within 2 years and shared responsibilities': 'متوافقان على الإنجاب خلال سنتين وتقاسم المسؤوليات',
  'Both ready for Nikah within 12 months': 'كلاهما مستعد للنكاح خلال 12 شهراً',
  'Location & relocation': 'الموقع والانتقال',
  'Same city; one is open to relocating after marriage': 'المدينة نفسها؛ وأحدهما منفتح على الانتقال بعد الزواج',
  '🎖️ Marriage Readiness': '🎖️ الجاهزية للزواج',
  'Know Who Is Actually Ready for Nikah': 'اعرف من هو مستعد فعلاً للنكاح',
  'Every member earns a Marriage Readiness badge based on verified behavior — not self-promotion. Filter your candidates by readiness so no one wastes your time.': 'كل عضو يحصل على شارة جاهزية بناءً على سلوك موثق — لا ترويج ذاتي. صفِّ مرشحيك حسب الجاهزية حتى لا يضيع وقتك.',
  'Ready Now': 'مستعد الآن', 'Within 12 Months': 'خلال 12 شهراً', 'Exploring Marriage': 'يستكشف الزواج',
  'Family Involved': 'الأسرة مشاركة', 'Fully Verified': 'موثق بالكامل',
  'Fully prepared for Nikah and actively seeking': 'مستعد تماماً للنكاح ويبحث بجدية',
  'Committed to marriage within the coming year': 'ملتزم بالزواج خلال العام القادم',
  'Serious about marriage, still defining the timeline': 'جاد في الزواج ويحدد الجدول الزمني',
  'Wali or family actively participating in the search': 'الولي أو الأسرة يشاركان في البحث',
  'ID, face, and phone verification all complete': 'اكتمال توثيق الهوية والوجه والهاتف',
  'Your readiness score is built from:': 'تُحسب درجة جاهزيتك من:',
  'Verification completion': 'اكتمال التوثيق', 'Profile completeness': 'اكتمال الملف',
  'Marriage intent assessment': 'تقييم نية الزواج', 'Lifestyle assessment': 'تقييم نمط الحياة',
  'Financial stability questions': 'أسئلة الاستقرار المالي',
  'Communication behavior': 'سلوك التواصل',
  '👨‍👩‍👧 Family Participation': '👨‍👩‍👧 مشاركة الأسرة',
  'Marriage Is a Family Matter — So Is Nikah': 'الزواج شأن أسري — وكذلك نكاح',
  'The only platform where wali and family involvement is a first-class feature, not an afterthought. Every family tool is optional and controlled by you.': 'المنصة الوحيدة التي تجعل مشاركة الولي والأسرة ميزة أساسية لا إضافة لاحقة. كل أدوات الأسرة اختيارية وتحت سيطرتك.',
  'Parent Accounts': 'حسابات الوالدين',
  'Parents can hold their own linked account to follow and support the search.': 'يمكن للوالدين امتلاك حساب مرتبط لمتابعة البحث ودعمه.',
  'Wali Participation': 'مشاركة الولي',
  'A wali can be invited into any introduction from the very first message.': 'يمكن دعوة الولي إلى أي تعارف من أول رسالة.',
  'Family-Assisted Search': 'بحث بمساعدة الأسرة',
  'Family members can browse and shortlist candidates on your behalf.': 'يمكن لأفراد الأسرة تصفح المرشحين وترشيح الأنسب نيابة عنك.',
  'Family Review of Proposals': 'مراجعة أسرية للعروض',
  'Proposals can require family approval before an introduction begins.': 'يمكن اشتراط موافقة الأسرة على العرض قبل بدء التعارف.',
  'Chaperoned Conversations': 'محادثات بمرافقة',
  'Conversations can include a chaperone who sees every message.': 'يمكن أن تضم المحادثات مرافقاً يرى كل رسالة.',
  'Family Dashboard': 'لوحة الأسرة',
  'A dedicated view of active introductions, proposals, and progress.': 'عرض مخصص للتعارفات النشطة والعروض وسير التقدم.',
  'Suggestions for Parents': 'اقتراحات للوالدين',
  'Compatible candidate suggestions parents can pass to their son or daughter.': 'اقتراحات مرشحين متوافقين يمررها الوالدان لابنهما أو ابنتهما.',
  'Family Visibility Settings': 'إعدادات ظهور الأسرة',
  'You choose exactly what your family can see — full, partial, or summary.': 'أنت تحدد بدقة ما تراه أسرتك — كامل أو جزئي أو ملخص.',
  '🚫 Our Anti-Scam Commitment': '🚫 التزامنا بمكافحة الاحتيال',
  'Zero Tolerance. Enforced by Systems and People.': 'صفر تسامح. تطبيق بالأنظمة والبشر.',
  'Marriage scams target hopeful people at their most trusting. We treat scam prevention as a core product feature — not a help-center page.': 'احتيال الزواج يستهدف أشخاصاً مفعمين بالأمل في أكثر لحظاتهم ثقة. نتعامل مع منع الاحتيال كميزة أساسية في المنتج — لا صفحة مساعدة.',
  'Never allowed on Nikah': 'ممنوع نهائياً على نكاح',
  'Requests for money': 'طلبات المال',
  'Gift card requests': 'طلبات بطاقات الهدايا',
  'Crypto or investment schemes': 'مخططات العملات الرقمية أو الاستثمار',
  'Fake overseas marriage requests': 'طلبات زواج خارجية وهمية',
  'Unverified profiles messaging freely': 'مراسلة حرة لملفات غير موثقة',
  'Multiple hidden accounts': 'حسابات مخفية متعددة',
  'Harassment of any kind': 'أي نوع من التحرش',
  'Suspicious mass messaging': 'رسائل جماعية مشبوهة',
  'Automatic Detection & Risk Scoring': 'كشف تلقائي وتقييم للمخاطر',
  'Message patterns, account behavior, and reports feed a risk score. High-risk accounts are flagged before they can reach more members.': 'أنماط الرسائل وسلوك الحساب والبلاغات تُغذي درجة المخاطر. تُعلَّم الحسابات عالية الخطورة قبل وصولها لمزيد من الأعضاء.',
  'Warnings & Restrictions': 'تحذيرات وقيود',
  'Risky behavior triggers warnings and messaging restrictions immediately — a suspicious account cannot keep contacting people while under review.': 'السلوك الخطر يستدعي تحذيرات وقيوداً فورية على المراسلة — لا يستطيع الحساب المشبوه مواصلة التواصل أثناء المراجعة.',
  'Manual Review & Permanent Bans': 'مراجعة يدوية وحظر دائم',
  'A human moderator reviews every flagged account. Confirmed scammers are permanently banned and their verification details blocked from re-registering.': 'مشرف بشري يراجع كل حساب مُبلغ عنه. يُحظر المحتالون المؤكدون نهائياً وتُمنع بيانات توثيقهم من إعادة التسجيل.',
  'Refunds When Applicable': 'استرداد المال عند الاقتضاء',
  'If a paying member is harmed by a failure of our safety systems, we review the case for a refund. We stand behind our protection.': 'إذا تضرر عضو مدفوع بسبب خلل في أنظمتنا الأمنية، ندرس حالته للاسترداد. نحن نقف خلف حمايتنا.',
  '📊 Transparency': '📊 الشفافية',
  'We Publish the Numbers That Matter': 'ننشر الأرقام المهمة',
  'No inflated member counts. As the platform grows, these metrics are reported live and audited in our annual transparency report.': 'لا أعداد أعضاء مضخمة. مع نمو المنصة تُنشر هذه المؤشرات مباشرة وتُدقق في تقرير الشفافية السنوي.',
  'Verified profile percentage': 'نسبة الملفات الموثقة',
  'Successful marriages reported': 'زيجات ناجحة مُبلغ عنها',
  'Average first response time': 'متوسط زمن أول رد',
  'Scam reports resolved < 24h': 'بلاغات احتيال حُلت خلال 24 ساعة',
  'Profile approval rate': 'معدل قبول الملفات',
  'Fraud attempts blocked': 'محاولات احتيال محظورة',
  'Languages supported': 'لغات مدعومة',
  'Metrics marked “—” will display live data at launch. We do not publish estimates or invented figures.': 'المؤشرات المعلمة بـ«—» ستعرض بيانات حقيقية عند الإطلاق. لا ننشر تقديرات ولا أرقاماً مختلقة.',
  'Everything We Do Is Documented in the Trust Center': 'كل ما نقوم به موثق في مركز الثقة',
  'How verification works, how moderation decisions are made, how your data is protected, and how we report on it — all public, all in one place.': 'كيف يعمل التوثيق، وكيف تُتخذ قرارات الإشراف، وكيف تُحمى بياناتك، وكيف ننشر التقارير — كل ذلك علني وفي مكان واحد.',
  'Verification Standards': 'معايير التوثيق',
  'Scam Prevention': 'منع الاحتيال',
  'Moderation Process': 'عملية الإشراف',
  'Data Privacy': 'خصوصية البيانات',
  'Community Guidelines': 'قواعد المجتمع',
  'Transparency Reports': 'تقارير الشفافية',
  'Visit the Trust Center →': 'زر مركز الثقة ←',
}

const SO: Dict = {
  'Government ID Verification': 'Xaqiijinta Aqoonsiga Dawladda',
  'Face Verification': 'Xaqiijinta Wajiga',
  'Phone Verification': 'Xaqiijinta Telefoonka',
  'Marriage Intent Screening': 'Baaritaanka Niyada Guurka',
  'Scam Detection': 'Kashifidda Khiyaanada',
  'Family Participation': 'Ka-qaybgalka Qoyska',
  'Human Moderation': 'Kormeer Bini\'aadam',
  'Privacy Controls': 'Xakamaynta Sirta',
  'No Casual Dating': 'Ma jiro Shukaansi Fudud',
  'Profiles reviewed': 'Profiles la eegay',
  'Report response': 'Jawaabta warbixinta',
  'Countries served': 'Wadamada la adeegayo',
  '🪪 ID-Verified Members': '🪪 Xubno Aqoonsi la Xaqiijiyay',
  '👨‍👩‍👧 Family & Wali Involved': '👨‍👩‍👧 Qoyska iyo Waligu wey ka Qaybqaataan',
  '🕌 Marriage Intent Screened': '🕌 Niyada Guurka waa la Baaray',
  '🚫 No Casual Dating': '🚫 Ma jiro Shukaansi Fudud',
  'Serving Muslim communities in 50+ countries': 'Waxaan u adeegnaa bulshooyinka Muslimiinta 50+ waddan',
  '⚠️ Why Nikah Exists': '⚠️ Sababta Nikah u Jiro',
  'The Problems Other Platforms Ignore': 'Dhibaatooyinka ay Barnaamijyada Kale Iska Indhatiraan',
  'Muslims seeking marriage deserve better than fake profiles, scams, and casual chatting. Nikah was built to remove each of these obstacles.': 'Muslimiinta guur raadinaya waxay mudan yihiin wax ka wanaagsan profiles been ah, khiyaano, iyo sheeko aan ujeedo lahayn. Nikah waxaa loo dhisay in laga saaro caqabad kasta oo kuwan ka mid ah.',
  'Fake profiles': 'Profiles been ah',
  'Scammers': 'Khiyaanoolayaal',
  'Endless messaging with no outcome': 'Fariimo aan dhammaanayn oo aan natiijo lahayn',
  'Unsafe interactions': 'Isdhexgal aan ammaan ahayn',
  'Families left out': 'Qoysas la iska indhatiray',
  'No serious marriage intent': 'Niyad guur oo dhab ah oo maqan',
  'Every member completes government ID, face, and phone verification before they can freely interact.': 'Xubin kastaa waxay dhammaystirtaa xaqiijinta aqoonsiga, wajiga, iyo telefoonka ka hor inta aysan si xor ah u wada xiriirin.',
  'AI risk scoring, message pattern detection, and human review catch money requests and romance scams early.': 'Qiimaynta khatarta ee AI, kashifidda qaababka fariimaha, iyo eegis bini\'aadam ayaa goor hore qabta codsiyada lacagta iyo khiyaanada jacaylka.',
  'Structured introductions with marriage timelines, so conversations move toward a decision — not years of chatting.': 'Is-baratan habaysan oo leh jadwal guur, si wada-hadaladu u aadaan go\'aan — ma aha sanado sheeko ah.',
  'Chaperoned conversations, photo protection, consent-based messaging, and moderators who answer reports within 24 hours.': 'Wada-hadal la kormeerayo, ilaalinta sawirrada, fariimo ogolaansho ku salaysan, iyo kormeerayaal ka jawaaba warbixinnada 24 saacadood gudahood.',
  'Wali and parent accounts, family review of proposals, and a family dashboard — involvement is built in, not bolted on.': 'Akoonno wali iyo waalid, eegis qoys oo soo-jeedinnada ah, iyo shaashad qoys — ka-qaybgalku waa mid ku dhex dhisan.',
  'Marriage intent screening and readiness badges filter out anyone who is not genuinely pursuing Nikah.': 'Baaritaanka niyada guurka iyo calaamadaha diyaargarowga ayaa ka saara qof kasta oo aan si dhab ah u raadin Nikaax.',
  'Create a Verified Profile': 'Samee Profile la Xaqiijiyay',
  'Build a marriage-focused profile stating your faith, values, family expectations, and marriage intentions — reviewed before it goes live.': 'Dhis profile guur ku salaysan oo muujinaya iimaankaaga, qiyamkaaga, rajada qoyskaaga, iyo niyadaada guur — waa la eegaa ka hor inta aan la daabicin.',
  'Marriage intent stated upfront': 'Niyada guurka horay loo sheegay',
  'Profile reviewed by a human': 'Profile uu eegay bini\'aadam',
  'Photo privacy controls': 'Xakamaynta sirta sawirrada',
  'Verify Your Identity': 'Xaqiiji Aqoonsigaaga',
  'Complete government ID, face, and phone verification. Every member you meet is a real, accountable person — no anonymous profiles.': 'Dhammaystir xaqiijinta aqoonsiga, wajiga, iyo telefoonka. Xubin kasta oo aad la kulanto waa qof dhab ah oo la xisaabtami karo — ma jiraan profiles qarsoon.',
  'Government ID check': 'Hubinta aqoonsiga dawladda',
  'Face verification': 'Xaqiijinta wajiga',
  'Phone verification': 'Xaqiijinta telefoonka',
  'Complete Your Marriage Assessment': 'Dhammaystir Qiimayntaada Guurka',
  'Answer marriage-readiness and compatibility questions covering deen, prayer, madhab, family values, children, finances, and timeline.': 'Ka jawaab su\'aalaha diyaargarowga guurka iyo isu-ekaanshaha: diinta, salaadda, madhab-ka, qiyamka qoyska, carruurta, dhaqaalaha, iyo jadwalka.',
  'Marriage readiness score': 'Dhibcaha diyaargarowga guurka',
  'Faith & values assessment': 'Qiimaynta iimaanka iyo qiyamka',
  'Marriage timeline': 'Jadwalka guurka',
  'Receive Marriage Candidates': 'Hel Musharraxiin Guur',
  'We introduce you only to verified, compatible candidates who share your marriage timeline — with a compatibility score explained for each.': 'Waxaan ku barannaa oo keliya musharraxiin la xaqiijiyay oo kula mid ah jadwalkaaga guurka — mid kasta oo leh dhibco isu-ekaansho oo la sharraxay.',
  'Verified candidates only': 'Musharraxiin la xaqiijiyay oo keliya',
  'Compatibility explained': 'Isu-ekaansho la sharraxay',
  'Filter by readiness': 'Ku kala shaandhee diyaargarow',
  'Begin Introductions': 'Bilow Is-baratanka',
  'Start a chaperoned or private introduction with clear guidelines. Conversations are purpose-driven and protected by moderation.': 'Bilow is-baratan la kormeerayo ama gaar ah oo leh tilmaamo cad. Wada-hadaladu waa ujeedo leh oo kormeer bay ku ilaalsan yihiin.',
  'Chaperoned option': 'Doorasho kormeer leh',
  'Consent-based messaging': 'Fariimo ogolaansho ku salaysan',
  'Moderated conversations': 'Wada-hadal la kormeerayo',
  'Involve Families & Proceed to Nikah': 'Ka Qaybgeli Qoysaska oo u Gudub Nikaaxa',
  'Invite your wali, parents, or trusted family into the conversation and move toward Nikah with full transparency and Allah\'s blessing.': 'Ku casuumo waligaaga, waalidkaaga, ama qoyskaaga aad ku kalsoon tahay wada-hadalka, oo ugu gudub Nikaaxa daahfurnaan buuxda iyo barakada Allah.',
  'Wali/family invite': 'Casuumada wali/qoys',
  'Family review of proposals': 'Eegis qoys oo soo-jeedinnada ah',
  'Guided steps to Nikah': 'Tallaabooyin la hago oo Nikaax ah',
  'No credit card required · Cancel anytime': 'Kaadhka deynta looma baahna · Jooji wakhti kasta',
  'Members verify with a government-issued ID, face verification, and phone number — so every person you meet is real and accountable.': 'Xubnuhu waxay ku xaqiijiyaan aqoonsi dawladeed, xaqiijin waji, iyo lambar telefoon — qof kasta oo aad la kulanto waa dhab oo la xisaabtami karo.',
  'AI Fraud Detection': 'Kashifidda Khiyaanada ee AI',
  'Automated systems score risk, detect scam patterns like money requests and mass messaging, and restrict suspicious accounts before harm is done.': 'Nidaamyo otomaatig ah ayaa qiimeeya khatarta, kashifa qaababka khiyaanada sida codsiyada lacagta iyo fariimaha tirada badan, oo xaddida akoonnada shakiga leh ka hor dhibaato.',
  'A dedicated trust and safety team reviews every profile, every flagged conversation, and every verification submission — not just algorithms.': 'Koox u heellan kalsoonida iyo ammaanka ayaa eegta profile kasta, wada-hadal kasta oo la calaamadeeyay, iyo codsi kasta oo xaqiijin — ma aha algorithms oo keliya.',
  'Reports Answered in 24 Hours': 'Warbixinnada waxaa laga jawaabaa 24 Saacadood gudahood',
  'Report suspicious or inappropriate behavior instantly. A human moderator responds to every report within 24 hours.': 'Isla markiiba soo sheeg dhaqan shaki leh ama aan habboonayn. Kormeere bini\'aadam ayaa ka jawaaba warbixin kasta 24 saacadood gudahood.',
  'Photo Protection': 'Ilaalinta Sawirrada',
  'Photos are blurred by default and screenshots are discouraged. You approve exactly who can see your image — your photo, your control.': 'Sawirradu si toos ah ayay u mugdisan yihiin. Adigaa go\'aamiya cidda arki karta sawirkaaga — sawirkaaga, xakamayntaada.',
  'Private photo albums, hidden mode, granular visibility settings, and family-only viewing options protect you at every stage.': 'Albamo sawir oo gaar ah, hab qarsoon, dejinno muuqasho faahfaahsan, iyo aragti qoys-keliya ah ayaa ku ilaaliya marxalad kasta.',
  'Wali & Chaperone Mode': 'Habka Wali iyo Kormeeraha',
  'Invite a wali, parent, or trusted family member into any conversation for a fully transparent, family-supervised process.': 'Ku casuumo wali, waalid, ama qof qoys oo la aamini karo wada-hadal kasta si loo helo hab daahfuran oo qoys kormeerayo.',
  'Block & Restrict Tools': 'Qalabka Xannibaadda iyo Xaddidaadda',
  'Block anyone instantly without explanation. Restrict who can contact you to verified members only. Clear community guidelines, enforced.': 'Xannib qof kasta isla markiiba sharraxaad la\'aan. Ku xaddid cidda kula soo xiriiri karta xubnaha la xaqiijiyay oo keliya. Tilmaamo bulsho oo cad oo la dhaqan geliyay.',
  'Our safety commitments to': 'Ballanqaadyadayada ammaanka ee',
  'every member': 'xubin kasta',
  'Human moderators operate across time zones. These are standards we hold ourselves to — published in our Trust Center.': 'Kormeerayaal bini\'aadam ayaa ka shaqeeya aagagga waqtiga oo dhan. Kuwani waa heerar aan nafteenna ku qabanno — lagu daabacay Xarunta Kalsoonida.',
  'Profiles human-reviewed': 'Profiles uu eegay bini\'aadam',
  'Report response time': 'Waqtiga jawaabta warbixinta',
  'Tolerance for money requests': 'Dulqaadka codsiyada lacagta',
  'Data compliant': 'Waafaqsan xogta',
  'Visit the Trust Center': 'Booqo Xarunta Kalsoonida',
  '🧭 Marriage Compatibility': '🧭 Isu-ekaanshaha Guurka',
  'Compatibility Measured on What Marriage Is Built On': 'Isu-ekaansho lagu qiyaaso waxa guurku ku dhisan yahay',
  'Not photos and small talk — deen, family, children, finances, and timeline.': 'Ma aha sawirro iyo sheeko fudud — waa diin, qoys, carruur, dhaqaale, iyo jadwal.',
  'Every score is explained, so you understand': 'Dhibco kasta waa la sharraxaa, si aad u fahanto',
  'why': 'sababta',
  'a candidate is compatible.': 'uu musharraxu kugu haboon yahay.',
  'Assessed across 15 marriage dimensions': 'Lagu qiimeeyay 15 qaybood oo guur',
  'Deen & practice': 'Diinta iyo dhaqanka', 'Prayer frequency': 'Inta jeer ee salaadda', 'Madhab': 'Madhab',
  'Islamic knowledge': 'Aqoonta Islaamka', 'Family values': 'Qiyamka qoyska',
  'Children preference': 'Rabitaanka carruurta', 'Family involvement': 'Ka-qaybgalka qoyska',
  'Living arrangements': 'Hab-nololeedka guriga', 'Career goals': 'Yoolalka shaqada', 'Education': 'Waxbarashada',
  'Location': 'Goobta', 'Financial expectations': 'Rajooyinka dhaqaale',
  'Traditional vs modern roles': 'Doorar dhaqameed iyo casri', 'Relocation willingness': 'Diyaargarowga guurista goob',
  'Compatibility Report': 'Warbixinta Isu-ekaanshaha', '(example)': '(tusaale)',
  'You complete the assessment once during onboarding. We then introduce you only to verified candidates whose answers align with yours — and show you exactly where you align and where you differ, so families can make informed decisions together.': 'Qiimaynta hal mar ayaad dhammaystirtaa markaad isdiiwaangelinayso. Kadib waxaan ku barannaa oo keliya musharraxiin la xaqiijiyay oo jawaabahoodu kuwaaga waafaqsan yihiin — waxaana ku tusnaa meesha aad isku aragtaan iyo meesha aad ku kala duwan tihiin, si qoysasku go\'aan wada-ogaal ah u gaaraan.',
  'Deen & prayer': 'Diinta iyo salaadda',
  'Both pray five times daily and follow the same madhab': 'Labaduba shan jeer maalintii bay tukadaan waxayna raacaan isku madhab',
  'Both want family closely involved from the first introduction': 'Labaduba waxay rabaan qoys si dhow uga qaybqaata is-baratanka ugu horreeya',
  'Children & household': 'Carruurta iyo guriga',
  'Aligned on children within 2 years and shared responsibilities': 'Waxay isku raaceen carruur 2 sano gudahood iyo mas\'uuliyad wadaag ah',
  'Both ready for Nikah within 12 months': 'Labaduba waxay diyaar u yihiin Nikaax 12 bilood gudahood',
  'Location & relocation': 'Goobta iyo guurista',
  'Same city; one is open to relocating after marriage': 'Isku magaalo; midkood wuxuu diyaar u yahay inuu guuro guurka kadib',
  '🎖️ Marriage Readiness': '🎖️ Diyaargarowga Guurka',
  'Know Who Is Actually Ready for Nikah': 'Ogow cidda run ahaantii diyaar u ah Nikaaxa',
  'Every member earns a Marriage Readiness badge based on verified behavior — not self-promotion. Filter your candidates by readiness so no one wastes your time.': 'Xubin kastaa waxay ku kasbataa calaamad diyaargarow guur oo ku salaysan dhaqan la xaqiijiyay — ma aha is-faafin. Ku kala shaandhee musharraxiintaada diyaargarow si aan waqtigaaga loo lumin.',
  'Ready Now': 'Diyaar Hadda', 'Within 12 Months': '12 Bilood gudahood', 'Exploring Marriage': 'Baaraya Guurka',
  'Family Involved': 'Qoysku wuu ka Qaybqaataa', 'Fully Verified': 'Si Buuxda loo Xaqiijiyay',
  'Fully prepared for Nikah and actively seeking': 'Si buuxda ugu diyaarsan Nikaaxa oo si firfircoon u raadinaya',
  'Committed to marriage within the coming year': 'Ka go\'an guur sanadka soo socda gudihiisa',
  'Serious about marriage, still defining the timeline': 'Ka dhab ah guurka, jadwalkuse weli waa la qeexayaa',
  'Wali or family actively participating in the search': 'Wali ama qoys si firfircoon uga qaybqaadanaya raadinta',
  'ID, face, and phone verification all complete': 'Xaqiijinta aqoonsiga, wajiga, iyo telefoonka oo dhammaystiran',
  'Your readiness score is built from:': 'Dhibcahaaga diyaargarowga waxaa laga dhisaa:',
  'Verification completion': 'Dhammaystirka xaqiijinta', 'Profile completeness': 'Dhammaystirka profile-ka',
  'Marriage intent assessment': 'Qiimaynta niyada guurka', 'Lifestyle assessment': 'Qiimaynta hab-nololeedka',
  'Financial stability questions': 'Su\'aalaha xasilloonida dhaqaale',
  'Communication behavior': 'Dhaqanka isgaarsiinta',
  '👨‍👩‍👧 Family Participation': '👨‍👩‍👧 Ka-qaybgalka Qoyska',
  'Marriage Is a Family Matter — So Is Nikah': 'Guurku waa arrin qoys — Nikah-na sidaas oo kale',
  'The only platform where wali and family involvement is a first-class feature, not an afterthought. Every family tool is optional and controlled by you.': 'Barnaamijka kaliya ee ka-qaybgalka waliga iyo qoysku yahay astaan aasaasi ah, ma aha wax dib loogu daray. Qalab kasta oo qoys waa ikhtiyaari adigaana xakamaynaya.',
  'Parent Accounts': 'Akoonnada Waalidka',
  'Parents can hold their own linked account to follow and support the search.': 'Waalidku waxay yeelan karaan akoon u gaar ah oo ku xiran si ay ula socdaan raadinta oo ay u taageeraan.',
  'Wali Participation': 'Ka-qaybgalka Waliga',
  'A wali can be invited into any introduction from the very first message.': 'Wali waxaa lagu casuumi karaa is-baratan kasta laga bilaabo fariinta ugu horreysa.',
  'Family-Assisted Search': 'Raadin Qoys Caawinayo',
  'Family members can browse and shortlist candidates on your behalf.': 'Xubnaha qoysku waxay kuu baari karaan oo kuu soo xulan karaan musharraxiin.',
  'Family Review of Proposals': 'Eegista Qoyska ee Soo-jeedinnada',
  'Proposals can require family approval before an introduction begins.': 'Soo-jeedinnadu waxay u baahan karaan ogolaansho qoys ka hor inta aan is-baratanku bilaaban.',
  'Chaperoned Conversations': 'Wada-hadal la Kormeerayo',
  'Conversations can include a chaperone who sees every message.': 'Wada-hadaladu waxay yeelan karaan kormeere arka fariin kasta.',
  'Family Dashboard': 'Shaashadda Qoyska',
  'A dedicated view of active introductions, proposals, and progress.': 'Aragti gaar ah oo is-baratanada firfircoon, soo-jeedinnada, iyo horumarka.',
  'Suggestions for Parents': 'Soo-jeedinno Waalidka ah',
  'Compatible candidate suggestions parents can pass to their son or daughter.': 'Soo-jeedinno musharraxiin ku haboon oo waalidku u gudbin karaan wiilkooda ama gabadhooda.',
  'Family Visibility Settings': 'Dejinta Muuqashada Qoyska',
  'You choose exactly what your family can see — full, partial, or summary.': 'Adigaa dooranaya waxa qoyskaagu arki karo — dhammaan, qayb, ama soo-koobid.',
  '🚫 Our Anti-Scam Commitment': '🚫 Ballanqaadkayaga ka-hortagga Khiyaanada',
  'Zero Tolerance. Enforced by Systems and People.': 'Dulqaad eber ah. Waxaa dhaqan geliya nidaamyo iyo dad.',
  'Marriage scams target hopeful people at their most trusting. We treat scam prevention as a core product feature — not a help-center page.': 'Khiyaanada guurku waxay bartilmaameedsataa dad rajo leh markay ugu kalsoonida badan yihiin. Ka-hortagga khiyaanadu waa astaan aasaasi ah oo alaabtayada ah — ma aha bog caawimaad.',
  'Never allowed on Nikah': 'Waligeed laguma ogola Nikah',
  'Requests for money': 'Codsiyo lacag',
  'Gift card requests': 'Codsiyo kaadh hadiyad',
  'Crypto or investment schemes': 'Qorshayaal crypto ama maalgashi',
  'Fake overseas marriage requests': 'Codsiyo guur dibedda oo been ah',
  'Unverified profiles messaging freely': 'Profiles aan la xaqiijin oo si xor ah u farriin diraya',
  'Multiple hidden accounts': 'Akoonno badan oo qarsoon',
  'Harassment of any kind': 'Dhibaatayn nooc kasta ah',
  'Suspicious mass messaging': 'Fariimo tiro badan oo shaki leh',
  'Automatic Detection & Risk Scoring': 'Kashifid Otomaatig ah iyo Qiimayn Khatar',
  'Message patterns, account behavior, and reports feed a risk score. High-risk accounts are flagged before they can reach more members.': 'Qaababka fariimaha, dhaqanka akoonka, iyo warbixinnadu waxay quudiyaan dhibco khatar. Akoonnada khatarta sare waa la calaamadeeyaa ka hor intaysan gaarin xubno kale.',
  'Warnings & Restrictions': 'Digniino iyo Xaddidaado',
  'Risky behavior triggers warnings and messaging restrictions immediately — a suspicious account cannot keep contacting people while under review.': 'Dhaqan khatar leh wuxuu isla markiiba keenaa digniino iyo xaddidaad fariimo — akoon shaki leh ma sii wadi karo xiriirinta dadka inta la eegayo.',
  'Manual Review & Permanent Bans': 'Eegis Gacanta ah iyo Mamnuucid Joogto ah',
  'A human moderator reviews every flagged account. Confirmed scammers are permanently banned and their verification details blocked from re-registering.': 'Kormeere bini\'aadam ayaa eega akoon kasta oo la calaamadeeyay. Khiyaanoolayaasha la xaqiijiyay si joogto ah ayaa loo mamnuucaa, xogtooda xaqiijintana waa laga xanibaa dib-u-diiwaangelin.',
  'Refunds When Applicable': 'Lacag-celin marka ay Habboon tahay',
  'If a paying member is harmed by a failure of our safety systems, we review the case for a refund. We stand behind our protection.': 'Haddii xubin lacag bixisa ay waxyeello ka soo gaarto guuldarro nidaamyadayada ammaanka, waxaan eegnaa kiiska lacag-celin. Waxaan taagan nahay ilaalintayada.',
  '📊 Transparency': '📊 Daahfurnaan',
  'We Publish the Numbers That Matter': 'Waxaan daabacnaa tirooyinka muhiimka ah',
  'No inflated member counts. As the platform grows, these metrics are reported live and audited in our annual transparency report.': 'Ma jiraan tirooyin xubno oo la buunbuuniyay. Marka barnaamijku koro, tirakoobyadan si toos ah ayaa loo daabacaa waxaana lagu xisaabtamaa warbixinta daahfurnaanta sanadlaha ah.',
  'Verified profile percentage': 'Boqolkiiba profiles la xaqiijiyay',
  'Successful marriages reported': 'Guuro guulaystay oo la sheegay',
  'Average first response time': 'Celceliska waqtiga jawaabta koowaad',
  'Scam reports resolved < 24h': 'Warbixinno khiyaano oo la xalliyay < 24s',
  'Profile approval rate': 'Heerka ogolaanshaha profile-ka',
  'Fraud attempts blocked': 'Isku-dayo khiyaano oo la xannibay',
  'Languages supported': 'Luqado la taageerayo',
  'Metrics marked “—” will display live data at launch. We do not publish estimates or invented figures.': 'Tirakoobyada calaamadaysan "—" waxay muujin doonaan xog toos ah marka la furo. Ma daabacno qiyaaso ama tirooyin la hindisay.',
  'Everything We Do Is Documented in the Trust Center': 'Wax kasta oo aan qabanno waxaa lagu diiwaangeliyay Xarunta Kalsoonida',
  'How verification works, how moderation decisions are made, how your data is protected, and how we report on it — all public, all in one place.': 'Sida xaqiijintu u shaqayso, sida go\'aannada kormeerka loo gaaro, sida xogtaada loo ilaaliyo, iyo sida aan uga warbixinno — dhammaan waa fagaare, hal meel.',
  'Verification Standards': 'Heerarka Xaqiijinta',
  'Scam Prevention': 'Ka-hortagga Khiyaanada',
  'Moderation Process': 'Habka Kormeerka',
  'Data Privacy': 'Sirta Xogta',
  'Community Guidelines': 'Tilmaamaha Bulshada',
  'Transparency Reports': 'Warbixinnada Daahfurnaanta',
  'Visit the Trust Center →': 'Booqo Xarunta Kalsoonida →',
}

const DICTS: Partial<Record<LangCode, Dict>> = { FR, AR, SO }

/** Translate a content string; falls back to the English original. */
export function tr(lang: string, s: string): string {
  return DICTS[lang as LangCode]?.[s] ?? s
}
