import PageHero from '../components/PageHero'
import { Link } from 'react-router-dom'

const SECTIONS = [
  { title: '1. What Data We Collect', body: 'We collect information you provide directly (name, email, age, profile details, photos), information generated by your use of the app (matches viewed, messages sent, preferences), and technical data (device type, IP address, usage logs). We do not sell your data to third parties, ever.' },
  { title: '2. How We Use Your Data', body: 'We use your data to: provide and improve the Nikah service; match you with compatible profiles; send you relevant notifications; ensure safety and prevent fraud; comply with legal obligations; and communicate with you about your account. We do not use your data for advertising to third parties.' },
  { title: '3. Your Profile and Visibility', body: 'Your profile is visible to other registered Nikah members. Your photos are blurred by default and only shown to members you approve. You can control all visibility settings from your account settings at any time.' },
  { title: '4. Data Sharing', body: 'We do not sell your personal data. We share data only with: trusted service providers who help us operate the platform (under strict data processing agreements); law enforcement when required by law; and other users only as you explicitly authorise through the app.' },
  { title: '5. Data Retention', body: 'We retain your data as long as your account is active. When you delete your account, we permanently delete your profile, photos, and messages within 30 days. Some data may be retained for up to 90 days in backups. You can request full data deletion at any time by contacting privacy@nikahapp.com.' },
  { title: '6. Security', body: 'All data is encrypted in transit (TLS) and at rest (AES-256). We conduct regular security audits. Our team undergoes data protection training. We notify you within 72 hours of any data breach that affects your personal information, in accordance with GDPR.' },
  { title: '7. Your Rights (GDPR)', body: 'Under GDPR and applicable law, you have the right to: access your personal data; correct inaccurate data; request deletion of your data; restrict or object to processing; data portability; and lodge a complaint with a supervisory authority. Contact privacy@nikahapp.com to exercise any of these rights.' },
  { title: '8. Cookies', body: 'We use essential cookies to operate the platform and optional analytics cookies to improve it. You can manage cookie preferences at any time. See our Cookie Policy for full details.' },
  { title: '9. Children\'s Privacy', body: 'Nikah is for users aged 18 and over. We do not knowingly collect data from anyone under 18. If we discover a user is under 18, we delete their account immediately.' },
  { title: '10. Changes to This Policy', body: 'We may update this Privacy Policy from time to time. We will notify you of material changes via email and in-app notice at least 14 days in advance. Your continued use of the app after changes take effect constitutes acceptance.' },
  { title: '11. Contact', body: 'For privacy enquiries or to exercise your rights, contact our Data Protection Officer at privacy@nikahapp.com.' },
]

export default function PrivacyPage() {
  return (
    <div style={{ paddingTop: 64 }}>
      <PageHero label="🔒 Privacy" title="Privacy" titleHighlight="Policy" subtitle="Last updated: 1 June 2025 — Your privacy is a right, not an afterthought." />
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <div className="bg-white rounded-3xl border border-gray-100 shadow-sm p-8 space-y-7">
          <div className="flex flex-wrap gap-3 p-4 rounded-2xl" style={{ background: 'rgba(26,107,74,0.06)' }}>
            {['🔒 Data encrypted', '🚫 Never sold', '✅ GDPR compliant', '🗑️ Deletable anytime'].map(t => (
              <span key={t} className="text-xs font-medium px-3 py-1.5 rounded-full bg-white border border-gray-100 text-gray-700">{t}</span>
            ))}
          </div>
          {SECTIONS.map(s => (
            <div key={s.title}>
              <h2 className="font-bold text-gray-900 mb-2">{s.title}</h2>
              <p className="text-gray-600 text-sm leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>
        <p className="text-center text-gray-400 text-sm mt-8">
          Also see: <Link to="/cookies" className="hover:underline" style={{ color: '#1a6b4a' }}>Cookie Policy</Link> · <Link to="/terms" className="hover:underline" style={{ color: '#1a6b4a' }}>Terms of Service</Link>
        </p>
      </div>
    </div>
  )
}
